<?php
/**
 * PhpMongoAdmin (www.phpmongoadmin.com) by Masterforms Mobile & Web (MFMAW)
 * @version      privacy.php 1001 6/8/20, 1:00 am  Gilbert Rehling $
 * @package      privacy.php
 * @subpackage   Id
 * @link         https://github.com/php-mongo/admin PHP MongoDB Admin
 * @copyright    Copyright (c) 2020. Gilbert Rehling of MMFAW. All rights reserved. (www.mfmaw.com)
 * @licence      PhpMongoAdmin is Open Source and is released under the MIT licence model.
 * @author       Gilbert Rehling:  gilbert@phpmongoadmin.com (www.gilbert-rehling.com)
 *  php-mongo-admin - License conditions:
 *  Contributions via our suggestion box are welcome. https://phpmongotools.com/suggestions
 *  This web application is available as Free Software and has no implied warranty or guarantee of usability.
 *  See licence.txt for the complete licensing outline.
 *  See COPYRIGHT.php for copyright notices and further details.
 */

/*
|--------------------------------------------------------------------------
| Privacy policy content Language Lines
|--------------------------------------------------------------------------
|
| The following language lines are on the /privacy us page.
|
*/

return [

    "activeTitle" => "PHP Mongo Admin Website Privacy Policy",
    "intro" => "Your privacy is critically important to us. Here at PHP Mongo Admin we have a few fundamental principles:",
    "intro2" => "<ul><li>We don’t ask you for personal information unless we truly need it. (We can’t stand services that ask you for things like your gender or income level for no apparent reason.)</li><li>We don’t share your personal information with anyone except to comply with the law, develop our products, or protect our rights.</li><li>We don’t store personal information on our servers unless required for the on-going operation of one of our services.</li><li>In our classifieds products, we aim to make it as simple as possible for you to control what’s visible to the public, seen by search engines, kept private, and permanently deleted.</li></ul>",
    "p1" => "Below is our privacy policy which incorporates these goals: (Note, this privacy policy is available under a <a target=\"_blank\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Sharealike</a> license, which means you’re more than welcome to steal it and repurpose it for your own use, just make sure to replace references to us with ones to you, and if you want we’d appreciate a link to <a target=\"_blank\" href=\"http://www.adultmuse.com/\">adultmuse.com</a> somewhere on your site.)",
    "p2" => "If you have questions about deleting or correcting your personal data or if you are having difficulty with a function of the members area please contact our <a href=\"/#/contact-us\">support team</a>",
    "t3" => "Website Visitors",
    "p3" => "Like most website operators, PHP Mongo Admin collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. PHP Mongo Admins` purpose in collecting non-personally identifying information is to better understand how PHP Mongo Admins` visitors use its website. From time to time, PHP Mongo Admin may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.",
    "p4" => "PHP Mongo Admin also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users that are searching for and browsing 'Ads'. PHP Mongo Admin only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below, except that a blog commenter and Ad posters IP addresses and email addresses are visible and disclosed to the administrators of the blog or classifieds where the comment or 'Ad' was left.",
    "t5" => "Gathering of Personally-Identifying Information",
    "p5" => "Certain visitors to PHP Mongo Admins` websites choose to interact with PHP Mongo Admin in ways that require PHP Mongo Admin to gather personally-identifying information. The amount and type of information that PHP Mongo Admin gathers depends on the nature of the interaction. For example, we ask visitors who sign up for an 'Ads' account to provide a Name and Email address. Those who engage in transactions with PHP Mongo Admin – by purchasing 'Ad Booster' products for example – are asked to provide additional information, including as necessary the personal and financial information required to process those transactions, however, we will never directly ask any customer for Credit-Card details as we use external payment gatewqays such as PayPal. In each case, PHP Mongo Admin collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor’s interaction with PHP Mongo Admin. PHP Mongo Admin does not disclose personally-identifying information other than as described below. Any visitor(s) can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.",
    "t6" => "Aggregated Statistics",
    "p6" => "PHP Mongo Admin may collect statistics about the behavior of visitors to its websites. For instance, PHP Mongo Admin may monitor the most popular 'Ads' on the <a href=\"/#/latest\">Lastest Ads</a> page or use information logged during 'searches' to better understand website usage trends. PHP Mongo Admin may display this information publicly or provide it to others. However, PHP Mongo Admin does not disclose personally-identifying information other than as described below.",
    "t7" => "Protection of Certain Personally-Identifying Information",
    "p7" => "PHP Mongo Admin discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on PHP Mongo Admins` behalf or to provide services available at PHP Mongo Admins` websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using PHP Mongo Admins` websites, you consent to the transfer of such information to them. PHP Mongo Admin will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, PHP Mongo Admin discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when PHP Mongo Admin believes in good faith that disclosure is reasonably necessary to protect the property or rights of PHP Mongo Admin, third parties or the public at large. If you are a registered user or member of an PHP Mongo Admin website and have supplied your email address, PHP Mongo Admin may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with PHP Mongo Admin and our classifieds products. We primarily use our various product blogs to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. PHP Mongo Admin takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifiable information.",
    "t8" => "Cookies",
    "p8" => "A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. PHP Mongo Admin uses cookies to help PHP Mongo Admin identify and track visitors, their usage of PHP Mongo Admin website, and their website access preferences. PHP Mongo Admin visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using PHP Mongo Admins` websites, with the drawback that certain features of PHP Mongo Admin websites may not function properly without the aid of cookies.",
    "t9" => "Business Transfers",
    "p9" => "If PHP Mongo Admin, or substantially all of its assets, were acquired, or in the unlikely event that PHP Mongo Admin goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of PHP Mongo Admin may continue to use your personal information as set forth in this policy.",
    "t10" => "External Ads",
    "p10" => "External Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by PHP Mongo Admin and does not cover the use of cookies by any advertisers.",
    "t11" => "Classified Ads",
    "p11" => "Ads placed by registered users or members remain the Copyrighted &copy; property of said user or member up until the time they remove their ads from our database. PHP Mongo Admin accept no direct responsibility for the contact of ads place by users and memebrs, however we do reserve the right to un-publish or remove ads that are deemed to be unfit or unsuitable for the purpose of displaying as a classified ad or that the ad may be considered to be of a pornographic nature",
    "t12" => "Comments",
    "p12" => "Comments and other content such as 'Ads' submitted to our service are saved on our servers and remain under the explicit control of subscribers to the classifieds service and are only directly managed by us unless a user or members registration is cancelled or lapses, in which case we store them long enough to enable a subscriber to renew their registration using the same email address as before.",
    "t13" => "Privacy Policy Changes",
    "p13" => "Although most changes are likely to be minor, PHP Mongo Admin may change its Privacy Policy from time to time, and at PHP Mongo Admins` sole discretion. In such a case PHP Mongo Admin will notify registered users and members via email however PHP Mongo Admin also encourages visitors to frequently check this page for any changes to its Privacy Policy. If you have a phpmongoadmin.com/#/blog account, you should also check your blog’s dashboard for alerts to these changes. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change."

];
