<?php

/*
|--------------------------------------------------------------------------
| Terms & Conditions content Language Lines
|--------------------------------------------------------------------------
|
| The following language lines are on the /terms us page.
|
*/

return [

    "activeTitle" => "PHP Mongo Admin Website Terms and Conditions of Use",
    "intro" => "Contained herein are details that define our 'fair usage policy', the 'Terms' that are either implied explicitly or implicitly and also the 'Conditions of Use' which all visitors and registered users being either potential or current must agree to and abide by",
    "intro2" => "We also provide a 'Paid' video service where 'Members' pay to watch videos which you have uploaded. Income earned by your Uploaded Videos earns you credits which you can use to 'Boost' your 'Ads' into the Top-Ten listing positions.",
    "p1" => "This website is designated as a Classified service which offers the ability to post (place) 'Ads' for free (without any initial cost) for a time which is limited to a maximum period of 3 months",
    "p2" => "'Ads' which have 'not' been linked to any of the 'paid for' booster functions and have been published for 3 months or over will be automatically set to 'unpublished' every day by automated system functions.",
    "p3" => "All newly published 'Ads' will have an opportunity to be placed in the 'Top-Ten Ad' list relative to the selected 'Section and Category', however, this is dependent on the number of 'Ads' that are using the 'paid for' boosted ad functions at the time you publish your ad. 'Ads' that have been 'boosted' will always be given a higher positioning priority in the generated lists compared to 'Ads' which are not boosted.",
    "p4" => "As general rule, this website does 'Not' make available 'Free to View' pornographic material (videos and the like), however, we do offer a service which enables you to 'Upload Videos' into the 'Pay Per View' or (PPV Video) section. PPV Videos must be of suitable quality and content to warrant being made available in the PPV Video service. Any income generated by your 'Uploaded Videos' is placed as 'Credit' towards your account which can then be redeemed to 'Boost Ads' with the Ad Boost tools. You will be able to track 'all' activity that is generated by your 'Ads' and 'Videos' within the members area",
    "p5" => "We use PayPal for all payments for 'Ad Booster' tools. Our system will 'Never' require your Credit Card details. You may also earn redeemable credits by uploading 'Pay per View' videos.",
    "p6" => "PHP Mongo Admin Classified retains the right to amend and or update any of the above-mentioned Terms and Conditions at anytime without notice to you. Please ensure that you monitor this page for any changes in the future."

];
